export const SHOW_MODAL = "SHOW_MODAL"
export const HIDE_MODAL = "HIDE_MODAL"
export const DESTROY_MODAL = "DESTROY_MODAL"
export const CHANGE_SIDEBAR = "CHANGE_SIDEBAR"



export const NETWORK_ERROR = "NETWORK_ERROR"
export const SHOW_NETWORK_MODAL = "SHOW_NETWORK_MODAL"




export const START_ACTION = "START_ACTION"
export const STOP_ACTION = "STOP_ACTION"




export const FETCH_CATEGORY = "FETCH_CATEGORY"
export const FETCH_CATEGORY_SUCCESS = "FETCH_CATEGORY_SUCCESS"
export const FETCH_CATEGORY_FAILURE = "FETCH_CATEGORY_FAILURE"





export const FETCH_LATEST_VIDEO = "FETCH_LATEST_VIDEO"
export const FETCH_LATEST_VIDEO_SUCCESS = "FETCH_LATEST_VIDEO_SUCCESS"
export const FETCH_LATEST_VIDEO_FAILURE = "FETCH_LATEST_VIDEO_FAILURE"
